### ISSUE TITLE
Audiobus Pattern Triggers Dont Reflect State

### ISSUE THREAD

**Issue by AbleThought** [olympianoiseco/Patterning-2-Public#148]
Hi, hope this issue wasnt previously pointed out, I looked around. I am noticing that In audiobus remote the Pattern Trigger Buttons ( A, B, C ect ) that are selected do not reflect the state of patterning 2.

Say you have Pattern A and Pattern B ( In Audiobus Remote ) 

Say Pattern A is playing.

If you select Pattern B ( again through audiobus remote ) Pattern B will play however the ring in the AB remote trigger remains on A. 

An additional press on B will select B.. so essentially AB remote is requiring a double press to reflect state.

I thought this would be a good time to bring it up as AB midi control is coming out any day now.

Thanks!

**Comment by AbleThought** [comment]
Another couple issues. Im working in AB3 midi beta and noticed a few other things along these lines.

1 When Patterning 2 patterns are triggered from within Patterning 2, Audiobus remote triggers will not reflect the changes. In other words there is no indication in Audiobus remote that any change of patterns is happening.

2 i suppose this is a feature request but it would be nice if the pattern indicators showed up in the audiobus transport bar instead of just audiobus remote. The reason is AB3 midi update uses
 a midi learn function so any triggers that dont appear within audiobus cannot be assigned to a controller as far as i can tell.

**Comment by aplourde72** [comment]
In addition to the incorrect behavior in Audiobus Remote, Patterning 2 has an issue correctly displaying the pattern forward / back buttons in the Audiobus slide-over panel.

Basically, the icons don’t update until you get “past” the last pattern.

More specifically:

Assume you have three patterns: A, B, C
Initially you’re on A; in the Audiobus panel you see the pattern advance button solid and a greyed out pattern back (since you’re at the start of the pattern list)
When you start playing and press the advance button, Patterning 2 advances to pattern B, but the Audiobus panel doesn’t update.
Press a second time and you’re playing C, but the panel still hasn’t updated; it still looks like you’re on pattern A
Now press a third time.  The pattern playing doesn’t advance as you were already on the last pattern, but now the Audiobus panel updates to show you’re on the last panel.  I.e. the back button is now solid and the forward button is greyed out.

Going back to A behaves in the same, buggy, manner.

**Comment by aplourde72** [comment]
To be clear, the issue with the slide-over panel isn't just a cosmetic issue.  Because the back button is greyed out until you go "past" the last pattern there's no way to go backwards until you get to the last pattern (and advance one more time).  At that point you can only go backwards through the patterns until you get to the first pattern (and hit the button one additional time).

**Comment by olympianoiseco** [comment]
This issue should be fixed for version 2.2.1 (coming soon)
