### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by PascalLuethi1** [olympianoiseco/Patterning-2-Public#181]
Hi 
i‘m using patterning to control my shuttle system as well as sending out a clik track and samples. it works very well! there‘s 3 things that would make programming much easier for me:
1. it would be nice if it, when entering midi note values, would show the note somewhere. 
2. it would be cool if i could quantize the midi notes per pattern and not for the whole song. 
3. it would be absolutely amazing if i could give my patterns a custom name.

patterning rocks!
thanks
pascal

edit: starting the timeline from any position would be cool for rehearsals!

**Comment by olympianoiseco** [comment]
Hello!  Thanks for reaching out. 

 

> it would be nice if it, when entering midi note values, would show the note somewhere.
Check the top right hand corner when you are editing notes!

> it would be cool if i could quantize the midi notes per pattern and not for the whole song.
MIDI note quantize is stored with the instrument, as a part of a drum kit.  Since you can have multiple drum kits per song, you can have different quantization settings in a song using multiple drum kits. 

> it would be absolutely amazing if i could give my patterns a custom name.
I agree, it's a sort of weird holdover from Patterning 1, and not super easy to change at the moment.  Definitely on the long-term feature request list.
